{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 난임 환자 대상 임신 성공 여부 예측"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### LGAimers 6th 온라인 해커톤"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Import"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import lightgbm as lgb\n",
    "from sklearn.preprocessing import OrdinalEncoder\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "import lightgbm as lgb\n",
    "import xgboost as xgb\n",
    "from catboost import CatBoostClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Data Load"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 데이터 로드\n",
    "DI_train = pd.read_csv('../data/DI_train_dataset_53.csv')\n",
    "DI_test = pd.read_csv('../data/DI_test_dataset_53.csv')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 인코딩 "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "from autogluon.tabular import TabularDataset, TabularPredictor\n",
    "import autogluon.core as ag\n",
    "\n",
    "train_data = TabularDataset(DI_train)\n",
    "test_data = TabularDataset(DI_test)\n",
    "\n",
    "label = '임신_성공_여부'\n",
    "eval_metric = 'roc_auc'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Verbosity: 2 (Standard Logging)\n",
      "=================== System Info ===================\n",
      "AutoGluon Version:  1.2\n",
      "Python Version:     3.11.8\n",
      "Operating System:   Windows\n",
      "Platform Machine:   AMD64\n",
      "Platform Version:   10.0.19045\n",
      "CPU Count:          16\n",
      "Memory Avail:       9.82 GB / 15.86 GB (61.9%)\n",
      "Disk Space Avail:   174.17 GB / 476.30 GB (36.6%)\n",
      "===================================================\n",
      "Presets specified: ['best_quality']\n",
      "Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)\n",
      "Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1\n",
      "DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.\n",
      "\tThis is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.\n",
      "\tRunning DyStack for up to 900s of the 3600s of remaining time (25%).\n",
      "\tRunning DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.\n",
      "2025-02-25 00:37:13,695\tINFO worker.py:1810 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265 \u001b[39m\u001b[22m\n",
      "\t\tContext path: \"c:\\Users\\juneh\\OneDrive\\바탕 화면\\git_Aimers6th\\LG_Aimers_6th\\code\\AutogluonModels\\ag-20250224_code53_DI\\ds_sub_fit\\sub_fit_ho\"\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Running DyStack sub-fit ...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Beginning AutoGluon training ... Time limit = 893s\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m AutoGluon will save models to \"c:\\Users\\juneh\\OneDrive\\바탕 화면\\git_Aimers6th\\LG_Aimers_6th\\code\\AutogluonModels\\ag-20250224_code53_DI\\ds_sub_fit\\sub_fit_ho\"\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Train Data Rows:    5592\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Train Data Columns: 34\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Label Column:       임신_성공_여부\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Problem Type:       binary\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Preprocessing data ...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Selected class <--> label mapping:  class 1 = 1, class 0 = 0\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Using Feature Generators to preprocess the data ...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting AutoMLPipelineFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tAvailable Memory:                    9517.58 MB\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tTrain Data (Original)  Memory Usage: 1.78 MB (0.0% of available memory)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tInferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tStage 1 Generators:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tFitting AsTypeFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t\tNote: Converting 17 features to boolean dtype as they only contain 2 unique values.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tStage 2 Generators:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tFitting FillNaFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tStage 3 Generators:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tFitting IdentityFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tFitting CategoryFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t\tFitting CategoryMemoryMinimizeFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tStage 4 Generators:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tFitting DropUniqueFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tStage 5 Generators:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tFitting DropDuplicatesFeatureGenerator...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tUnused Original Features (Count: 1): ['ID']\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tThese features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tFeatures can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\tThese features do not need to be present at inference time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t('object', []) : 1 | ['ID']\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tTypes of features in original data (raw dtype, special dtypes):\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t('float', []) :  5 | ['시술_당시_나이', '임신_시도_또는_마지막_임신_경과_연수', 'IVF_임신_시술_비율', 'DI_임신_시술_비율', '임신_성공률']\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t('int', [])   : 28 | ['배란_자극_여부', '남성_주_불임_원인', '남성_부_불임_원인', '여성_주_불임_원인', '여성_부_불임_원인', ...]\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tTypes of features in processed data (raw dtype, special dtypes):\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t('float', [])     :  5 | ['시술_당시_나이', '임신_시도_또는_마지막_임신_경과_연수', 'IVF_임신_시술_비율', 'DI_임신_시술_비율', '임신_성공률']\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t('int', [])       : 11 | ['총_시술_횟수', '클리닉_내_총_시술_횟수', 'IVF_시술_횟수', 'DI_시술_횟수', '총_임신_횟수', ...]\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t('int', ['bool']) : 17 | ['배란_자극_여부', '남성_주_불임_원인', '남성_부_불임_원인', '여성_주_불임_원인', '여성_부_불임_원인', ...]\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.1s = Fit runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t33 features in original data used to generate 33 features in processed data.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tTrain Data (Processed) Memory Usage: 0.77 MB (0.0% of available memory)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Data preprocessing and feature engineering runtime = 0.14s ...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m AutoGluon will gauge predictive performance using evaluation metric: 'roc_auc'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tThis metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tTo change this, specify the eval_metric parameter of Predictor()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Large model count detected (112 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m User-specified model hyperparameters to be fit:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m {\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m }\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m AutoGluon will fit 2 stack levels (L1 to L2) ...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting 110 L1 models, fit_strategy=\"sequential\" ...\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 594.91s of the 892.58s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.5772\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.0s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.12s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 592.78s of the 890.45s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.5717\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.05s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 592.71s of the 890.39s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.12%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6696\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t1.06s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: LightGBM_BAG_L1 ... Training model for up to 588.72s of the 886.39s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.13%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6586\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.85s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 584.56s of the 882.24s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6072\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.77s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.2s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 583.53s of the 881.20s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6121\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.2s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: CatBoost_BAG_L1 ... Training model for up to 582.65s of the 880.32s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.19%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6759\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t2.46s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 577.28s of the 874.95s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6056\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.67s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.23s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 576.29s of the 873.97s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6067\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.51s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.2s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 575.50s of the 873.17s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.10%)\n",
      "\u001b[36m(_ray_fit pid=16652)\u001b[0m No improvement since epoch 7: early stopping\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6534\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t9.77s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.12s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: XGBoost_BAG_L1 ... Training model for up to 562.72s of the 860.40s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.25%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.662\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t1.84s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.02s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 557.38s of the 855.05s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.08%)\n",
      "\u001b[36m(_ray_fit pid=19372)\u001b[0m No improvement since epoch 8: early stopping\u001b[32m [repeated 3x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tWarning: Exception caused NeuralNetTorch_BAG_L1 to fail during training... Skipping this model.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=24392, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Detailed Traceback:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 2106, in _train_and_save\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = self._train_single(**model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 1993, in _train_single\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\stacker_ensemble_model.py\", line 270, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 298, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._fit_folds(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 724, in _fit_folds\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_fitting_strategy.after_all_folds_scheduled()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 690, in after_all_folds_scheduled\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 631, in _run_parallel\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._process_fold_results(finished, unfinished, fold_ctx)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 587, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise processed_exception\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 550, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2753, in get\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 904, in get_objects\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise value.as_instanceof_cause()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m ray.exceptions.RayTaskError(TypeError): \u001b[36mray::_ray_fit()\u001b[39m (pid=24392, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 551.10s of the 848.77s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.35%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6395\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t1.39s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 546.40s of the 844.08s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.22%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6801\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t2.75s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 540.23s of the 837.90s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.06%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tWarning: Exception caused NeuralNetTorch_r79_BAG_L1 to fail during training... Skipping this model.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=19804, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Detailed Traceback:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 2106, in _train_and_save\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = self._train_single(**model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 1993, in _train_single\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\stacker_ensemble_model.py\", line 270, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 298, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._fit_folds(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 724, in _fit_folds\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_fitting_strategy.after_all_folds_scheduled()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 690, in after_all_folds_scheduled\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 631, in _run_parallel\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._process_fold_results(finished, unfinished, fold_ctx)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 587, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise processed_exception\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 550, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2753, in get\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 904, in get_objects\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise value.as_instanceof_cause()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m ray.exceptions.RayTaskError(TypeError): \u001b[36mray::_ray_fit()\u001b[39m (pid=19804, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 534.04s of the 831.71s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.19%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6566\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t1.58s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 529.22s of the 826.89s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.12%)\n",
      "\u001b[36m(_ray_fit pid=5424)\u001b[0m No improvement since epoch 6: early stopping\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.648\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t22.08s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.21s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 503.74s of the 801.42s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.69%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6709\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t6.21s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 494.40s of the 792.07s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.11%)\n",
      "\u001b[36m(_ray_fit pid=21368)\u001b[0m No improvement since epoch 20: early stopping\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6718\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t1.14s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.06s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 490.01s of the 787.68s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.07%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tWarning: Exception caused NeuralNetTorch_r22_BAG_L1 to fail during training... Skipping this model.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=20112, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Detailed Traceback:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 2106, in _train_and_save\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = self._train_single(**model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 1993, in _train_single\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\stacker_ensemble_model.py\", line 270, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 298, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._fit_folds(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 724, in _fit_folds\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_fitting_strategy.after_all_folds_scheduled()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 690, in after_all_folds_scheduled\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 631, in _run_parallel\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._process_fold_results(finished, unfinished, fold_ctx)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 587, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise processed_exception\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 550, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2753, in get\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 904, in get_objects\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise value.as_instanceof_cause()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m ray.exceptions.RayTaskError(TypeError): \u001b[36mray::_ray_fit()\u001b[39m (pid=20112, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 483.81s of the 781.48s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=1.41%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6406\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t2.72s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.06s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 477.70s of the 775.37s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6045\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.87s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.24s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 476.48s of the 774.15s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.11%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6825\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t2.57s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.02s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 470.65s of the 768.33s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.13%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.658\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t6.0s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.06s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 460.96s of the 758.63s of remaining time.\n",
      "\u001b[36m(_ray_fit pid=4328)\u001b[0m No improvement since epoch 8: early stopping\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.86%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6742\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t5.45s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 451.62s of the 749.29s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6147\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.83s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.18s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 450.52s of the 748.19s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.38%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6501\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t1.38s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.02s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 445.81s of the 743.48s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.13%)\n",
      "\u001b[36m(_ray_fit pid=1624)\u001b[0m No improvement since epoch 6: early stopping\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6483\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t17.6s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.17s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 424.78s of the 722.46s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.30%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6632\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t1.82s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.03s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 419.47s of the 717.14s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.09%)\n",
      "\u001b[36m(_ray_fit pid=5480)\u001b[0m No improvement since epoch 9: early stopping\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tWarning: Exception caused NeuralNetTorch_r30_BAG_L1 to fail during training... Skipping this model.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=17832, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Detailed Traceback:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 2106, in _train_and_save\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = self._train_single(**model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 1993, in _train_single\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\stacker_ensemble_model.py\", line 270, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 298, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._fit_folds(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 724, in _fit_folds\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_fitting_strategy.after_all_folds_scheduled()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 690, in after_all_folds_scheduled\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 631, in _run_parallel\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._process_fold_results(finished, unfinished, fold_ctx)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 587, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise processed_exception\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 550, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2753, in get\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 904, in get_objects\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise value.as_instanceof_cause()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m ray.exceptions.RayTaskError(TypeError): \u001b[36mray::_ray_fit()\u001b[39m (pid=17832, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 413.35s of the 711.02s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.32%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6585\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.82s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.01s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 409.32s of the 706.99s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.08%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tWarning: Exception caused NeuralNetTorch_r86_BAG_L1 to fail during training... Skipping this model.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t\t\u001b[36mray::_ray_fit()\u001b[39m (pid=11956, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Detailed Traceback:\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 2106, in _train_and_save\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = self._train_single(**model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\trainer\\abstract_trainer.py\", line 1993, in _train_single\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\stacker_ensemble_model.py\", line 270, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 298, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._fit_folds(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\bagged_ensemble_model.py\", line 724, in _fit_folds\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_fitting_strategy.after_all_folds_scheduled()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 690, in after_all_folds_scheduled\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 631, in _run_parallel\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self._process_fold_results(finished, unfinished, fold_ctx)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 587, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise processed_exception\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 550, in _process_fold_results\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size, fit_num_cpus, fit_num_gpus = self.ray.get(finished)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                                                                                                                      ^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\auto_init_hook.py\", line 21, in auto_init_wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return fn(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 103, in wrapper\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return func(*args, **kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 2753, in get\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ray\\_private\\worker.py\", line 904, in get_objects\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     raise value.as_instanceof_cause()\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m ray.exceptions.RayTaskError(TypeError): \u001b[36mray::_ray_fit()\u001b[39m (pid=11956, ip=127.0.0.1)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1862, in ray._raylet.execute_task\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\ensemble\\fold_fitting_strategy.py\", line 413, in _ray_fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **resources, **kwargs_fold)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\core\\models\\abstract\\abstract_model.py\", line 925, in fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     out = self._fit(**kwargs)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m           ^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 201, in _fit\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     train_dataset = self._generate_dataset(X, y, train_params=processor_kwargs, is_train=True)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 669, in _generate_dataset\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     dataset = self._process_train_data(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m               ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\torch\\tabular_nn_torch.py\", line 734, in _process_train_data\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     self.processor = create_preprocessor(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m                      ^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m   File \"c:\\Users\\juneh\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\autogluon\\tabular\\models\\tabular_nn\\utils\\data_preprocessor.py\", line 40, in create_preprocessor\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m     return ColumnTransformer(\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'force_int_remainder_cols'\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 403.27s of the 700.95s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.14%)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.679\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t2.5s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.0s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 397.62s of the 695.30s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.17%)\n",
      "\u001b[36m(_ray_fit pid=23660)\u001b[0m No improvement since epoch 10: early stopping\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.6628\t = Validation score   (roc_auc)\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t27.37s\t = Training   runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \t0.25s\t = Validation runtime\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 366.74s of the 664.41s of remaining time.\n",
      "\u001b[36m(_dystack pid=25896)\u001b[0m \tFitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=3, gpus=0, memory=0.69%)\n"
     ]
    }
   ],
   "source": [
    "from autogluon.tabular import TabularPredictor\n",
    "\n",
    "# 시간 제한 설정 \n",
    "time_limit =  1 * 60 * 60\n",
    "\n",
    "# # GPU를 사용할 수 없는 모델을 제외하도록 설정\n",
    "# exclude_model_types = [\n",
    "#     'KNN',  # K-Nearest Neighbors\n",
    "#     'RF',   # Random Forest\n",
    "#     'XT',   # Extra Trees\n",
    "#     'LR',   # Linear Regression\n",
    "#     'NN'    # Tabular Neural Network\n",
    "# ]\n",
    "\n",
    "# TabularPredictor 객체 생성 및 학습\n",
    "predictor = TabularPredictor(\n",
    "    label=label,\n",
    "    eval_metric=eval_metric,\n",
    "    path='AutogluonModels/ag-20250224_code53_DI'  # 모델 저장 경로\n",
    ").fit(\n",
    "    train_data,\n",
    "    presets='best_quality',  # 'best_quality', 'medium_quality', 'good_quality' 등의 프리셋 설정\n",
    "    # num_stack_levels=0,  # 스택 레벨 설정 / dynamic_stacking=True(디폴트)인 경우 무시\n",
    "    num_bag_folds=5,  # 배깅 설정\n",
    "    time_limit=time_limit,  # 시간 제한 설정\n",
    "    # num_gpus=1,  # GPU 사용 설정\n",
    "    # excluded_model_types=exclude_model_types  # 제외할 모델 유형 설정\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                          model  score_val eval_metric  pred_time_val  \\\n",
      "0           WeightedEnsemble_L3   0.725367     roc_auc       3.127192   \n",
      "1         ExtraTreesEntr_BAG_L2   0.718222     roc_auc       2.656744   \n",
      "2         ExtraTreesGini_BAG_L2   0.708253     roc_auc       2.667659   \n",
      "3            CatBoost_r9_BAG_L2   0.700075     roc_auc       2.476366   \n",
      "4             LightGBMXT_BAG_L2   0.699705     roc_auc       2.474246   \n",
      "5               CatBoost_BAG_L2   0.698803     roc_auc       2.455585   \n",
      "6           WeightedEnsemble_L2   0.690819     roc_auc       0.462723   \n",
      "7          CatBoost_r177_BAG_L2   0.689251     roc_auc       2.470236   \n",
      "8          CatBoost_r137_BAG_L1   0.687894     roc_auc       0.017632   \n",
      "9           CatBoost_r50_BAG_L1   0.686979     roc_auc       0.036760   \n",
      "10          LightGBM_r96_BAG_L2   0.686639     roc_auc       2.502582   \n",
      "11      RandomForestEntr_BAG_L2   0.686125     roc_auc       2.676092   \n",
      "12              CatBoost_BAG_L1   0.685897     roc_auc       0.018174   \n",
      "13          CatBoost_r13_BAG_L1   0.685120     roc_auc       0.017078   \n",
      "14         LightGBM_r131_BAG_L2   0.685119     roc_auc       2.464825   \n",
      "15              LightGBM_BAG_L2   0.683527     roc_auc       2.462040   \n",
      "16         CatBoost_r177_BAG_L1   0.683437     roc_auc       0.015626   \n",
      "17          CatBoost_r69_BAG_L1   0.682186     roc_auc       0.020379   \n",
      "18          CatBoost_r70_BAG_L1   0.681395     roc_auc       0.020897   \n",
      "19           CatBoost_r9_BAG_L1   0.680524     roc_auc       0.006552   \n",
      "20      RandomForestGini_BAG_L2   0.679538     roc_auc       2.656215   \n",
      "21          LightGBM_r96_BAG_L1   0.679136     roc_auc       0.046887   \n",
      "22              LightGBM_BAG_L1   0.676844     roc_auc       0.031783   \n",
      "23            LightGBMXT_BAG_L1   0.675480     roc_auc       0.007897   \n",
      "24           XGBoost_r89_BAG_L1   0.675129     roc_auc       0.015506   \n",
      "25  NeuralNetFastAI_r143_BAG_L1   0.675020     roc_auc       0.097995   \n",
      "26         LightGBM_r130_BAG_L1   0.674602     roc_auc       0.000000   \n",
      "27         LightGBM_r131_BAG_L1   0.672927     roc_auc       0.015626   \n",
      "28   NeuralNetFastAI_r11_BAG_L1   0.672852     roc_auc       0.287135   \n",
      "29               XGBoost_BAG_L1   0.672322     roc_auc       0.000000   \n",
      "30         LightGBMLarge_BAG_L2   0.672142     roc_auc       2.448641   \n",
      "31  NeuralNetFastAI_r191_BAG_L2   0.671418     roc_auc       2.666785   \n",
      "32          XGBoost_r194_BAG_L1   0.665165     roc_auc       0.067449   \n",
      "33  NeuralNetFastAI_r103_BAG_L1   0.664316     roc_auc       0.121196   \n",
      "34       NeuralNetFastAI_BAG_L2   0.663764     roc_auc       2.575482   \n",
      "35         LightGBM_r188_BAG_L1   0.656620     roc_auc       0.031268   \n",
      "36         LightGBMLarge_BAG_L1   0.655701     roc_auc       0.033294   \n",
      "37       ExtraTrees_r172_BAG_L1   0.654999     roc_auc       0.273572   \n",
      "38         LightGBM_r161_BAG_L1   0.651598     roc_auc       0.053154   \n",
      "39       NeuralNetFastAI_BAG_L1   0.648211     roc_auc       0.119833   \n",
      "40  NeuralNetFastAI_r145_BAG_L1   0.647058     roc_auc       0.166215   \n",
      "41               XGBoost_BAG_L2   0.638904     roc_auc       2.499801   \n",
      "42  NeuralNetFastAI_r191_BAG_L1   0.637791     roc_auc       0.186792   \n",
      "43  NeuralNetFastAI_r102_BAG_L1   0.635994     roc_auc       0.066770   \n",
      "44      RandomForestEntr_BAG_L1   0.634897     roc_auc       0.199933   \n",
      "45     RandomForest_r195_BAG_L1   0.631557     roc_auc       0.234785   \n",
      "46      RandomForestGini_BAG_L1   0.630684     roc_auc       0.206629   \n",
      "47        ExtraTrees_r42_BAG_L1   0.628988     roc_auc       0.256254   \n",
      "48        ExtraTreesGini_BAG_L1   0.626972     roc_auc       0.213809   \n",
      "49        ExtraTreesEntr_BAG_L1   0.624904     roc_auc       0.202573   \n",
      "50           XGBoost_r33_BAG_L2   0.610240     roc_auc       2.512896   \n",
      "51           XGBoost_r33_BAG_L1   0.584686     roc_auc       0.030550   \n",
      "52        KNeighborsUnif_BAG_L1   0.575343     roc_auc       0.257155   \n",
      "53        KNeighborsDist_BAG_L1   0.573841     roc_auc       0.055864   \n",
      "\n",
      "      fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  \\\n",
      "0   119.149461                0.001000           0.461098            3   \n",
      "1    90.926901                0.210329           0.611200            2   \n",
      "2    91.044171                0.221245           0.728470            2   \n",
      "3   114.075665                0.029952          23.759964            2   \n",
      "4    93.233000                0.027832           2.917299            2   \n",
      "5    97.899597                0.009170           7.583896            2   \n",
      "6    59.580088                0.000000           0.362496            2   \n",
      "7    97.290854                0.023821           6.975152            2   \n",
      "8     4.221373                0.017632           4.221373            1   \n",
      "9     4.098523                0.036760           4.098523            1   \n",
      "10   93.484859                0.056168           3.169157            2   \n",
      "11   91.354152                0.229678           1.038450            2   \n",
      "12    4.443961                0.018174           4.443961            1   \n",
      "13    7.398367                0.017078           7.398367            1   \n",
      "14   93.767988                0.018410           3.452287            2   \n",
      "15   93.029063                0.015626           2.713362            2   \n",
      "16    4.097918                0.015626           4.097918            1   \n",
      "17    4.151901                0.020379           4.151901            1   \n",
      "18    5.514240                0.020897           5.514240            1   \n",
      "19    8.287330                0.006552           8.287330            1   \n",
      "20   91.226251                0.209801           0.910549            2   \n",
      "21    2.502217                0.046887           2.502217            1   \n",
      "22    1.959680                0.031783           1.959680            1   \n",
      "23    1.211126                0.007897           1.211126            1   \n",
      "24    3.142190                0.015506           3.142190            1   \n",
      "25    9.409786                0.097995           9.409786            1   \n",
      "26    2.357283                0.000000           2.357283            1   \n",
      "27    2.638342                0.015626           2.638342            1   \n",
      "28   30.588433                0.287135          30.588433            1   \n",
      "29    3.428654                0.000000           3.428654            1   \n",
      "30   95.209882                0.002227           4.894181            2   \n",
      "31  114.431394                0.220371          24.115693            2   \n",
      "32    3.407973                0.067449           3.407973            1   \n",
      "33   16.880608                0.121196          16.880608            1   \n",
      "34  102.099071                0.129067          11.783370            2   \n",
      "35    2.633979                0.031268           2.633979            1   \n",
      "36    2.342480                0.033294           2.342480            1   \n",
      "37    0.920293                0.273572           0.920293            1   \n",
      "38    3.785657                0.053154           3.785657            1   \n",
      "39   11.750417                0.119833          11.750417            1   \n",
      "40   20.907492                0.166215          20.907492            1   \n",
      "41   92.983222                0.053386           2.667521            2   \n",
      "42   24.768458                0.186792          24.768458            1   \n",
      "43    7.550277                0.066770           7.550277            1   \n",
      "44    0.602863                0.199933           0.602863            1   \n",
      "45    0.991062                0.234785           0.991062            1   \n",
      "46    0.777361                0.206629           0.777361            1   \n",
      "47    1.041957                0.256254           1.041957            1   \n",
      "48    0.667218                0.213809           0.667218            1   \n",
      "49    0.603021                0.202573           0.603021            1   \n",
      "50   93.617747                0.066482           3.302046            2   \n",
      "51    2.615635                0.030550           2.615635            1   \n",
      "52    0.013624                0.257155           0.013624            1   \n",
      "53    0.006797                0.055864           0.006797            1   \n",
      "\n",
      "    can_infer  fit_order  \n",
      "0        True         54  \n",
      "1        True         44  \n",
      "2        True         43  \n",
      "3        True         51  \n",
      "4        True         38  \n",
      "5        True         42  \n",
      "6        True         37  \n",
      "7        True         48  \n",
      "8        True         20  \n",
      "9        True         28  \n",
      "10       True         52  \n",
      "11       True         41  \n",
      "12       True          7  \n",
      "13       True         22  \n",
      "14       True         49  \n",
      "15       True         39  \n",
      "16       True         13  \n",
      "17       True         32  \n",
      "18       True         36  \n",
      "19       True         16  \n",
      "20       True         40  \n",
      "21       True         17  \n",
      "22       True          4  \n",
      "23       True          3  \n",
      "24       True         26  \n",
      "25       True         35  \n",
      "26       True         27  \n",
      "27       True         14  \n",
      "28       True         29  \n",
      "29       True         11  \n",
      "30       True         47  \n",
      "31       True         50  \n",
      "32       True         30  \n",
      "33       True         33  \n",
      "34       True         45  \n",
      "35       True         24  \n",
      "36       True         12  \n",
      "37       True         31  \n",
      "38       True         34  \n",
      "39       True         10  \n",
      "40       True         25  \n",
      "41       True         46  \n",
      "42       True         15  \n",
      "43       True         21  \n",
      "44       True          6  \n",
      "45       True         23  \n",
      "46       True          5  \n",
      "47       True         19  \n",
      "48       True          8  \n",
      "49       True          9  \n",
      "50       True         53  \n",
      "51       True         18  \n",
      "52       True          1  \n",
      "53       True          2  \n"
     ]
    }
   ],
   "source": [
    "print(predictor.leaderboard(silent = True))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# predictor.feature_importance(train_data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 최적의 모델 가져오기\n",
    "model_to_use = predictor.model_best\n",
    "\n",
    "# 확률 예측\n",
    "prob_predictions = predictor.predict_proba(test_data, model=model_to_use)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "           ID  probability\n",
      "0  TEST_00026     0.083821\n",
      "1  TEST_00051     0.204894\n",
      "2  TEST_00076     0.011036\n",
      "3  TEST_00088     0.153002\n",
      "4  TEST_00100     0.100460\n"
     ]
    }
   ],
   "source": [
    "# 예측 결과를 test_data에 추가\n",
    "test_data['probability'] = prob_predictions.iloc[:, 1]\n",
    "\n",
    "# 최종 제출 파일 생성\n",
    "submission = test_data[['ID', 'probability']]\n",
    "submission = submission.sort_values(by='ID')\n",
    "\n",
    "# 제출 파일 저장\n",
    "submission.to_csv('../submission/code53_DI_lgbm2.csv', index=False, encoding='utf-8')\n",
    "\n",
    "# 예측 결과 확인\n",
    "print(submission.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "           ID  probability\n",
      "0  TEST_00000     0.001556\n",
      "1  TEST_00001     0.002249\n",
      "2  TEST_00002     0.151962\n",
      "3  TEST_00003     0.103942\n",
      "4  TEST_00004     0.512530\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-02-24 21:47:51,578\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2025-02-24 21:47:51,581\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2025-02-24 21:49:03,187\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2025-02-24 21:49:12,469\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2025-02-24 21:49:12,469\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2025-02-24 21:50:28,962\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2025-02-24 21:50:28,962\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n",
      "2025-02-24 21:50:28,962\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "# 첫 번째 제출 파일 읽기\n",
    "submission_ivf = pd.read_csv('../submission/code53_IVF_lgbm2.csv')\n",
    "submission_di = pd.read_csv('../submission/code53_DI_lgbm2.csv')\n",
    "\n",
    "# 두 데이터프레임 병합 (ID를 기준으로)\n",
    "merged_submission = pd.concat([submission_ivf, submission_di]).sort_values(by='ID')\n",
    "\n",
    "# 병합된 데이터프레임 저장\n",
    "merged_submission.to_csv('../submission/code53_merged_lgbm2.csv', index=False, encoding='utf-8')\n",
    "\n",
    "# 예측 결과 확인\n",
    "print(merged_submission.head())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "데이콘 PUBLIC xx"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "----"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
